apiVersion: v1
kind: ConfigMap
metadata:
  name: matrix-well-known
  namespace: matrix
data:
  "matrix-client.json": |
    {
      "m.homeserver": {
        "base_url": "https://matrixtoo.edgeinfra.site"
      },
      "m.identity_server": {
        "base_url": "https://vector.im"
      }
    }
  "matrix-server.json": |
    {
      "m.server": "matrixtoo.edgeinfra.site:443"
    }