apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "element.fullname" . }}
  labels:
    {{- include "element.labels" . | nindent 4 }}
data:
  config.json: |
    {{ toJson .Values.config | nindent 4 }}
