{{- if .Values.secret.generate -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "matrix.fullname" . }}-secret
  labels:
    {{- include "matrix.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "matrix.fullname" . }}-secret
  labels:
    {{- include "matrix.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "create", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "matrix.fullname" . }}-secret
  labels:
    {{- include "matrix.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "matrix.fullname" . }}-secret
subjects:
  - kind: ServiceAccount
    name: {{ include "matrix.fullname" . }}-secret
    namespace: {{ .Release.Namespace }}
{{- end }}
